// Master presentation examples (read-only templates).
// Each spec feeds presentationModel.buildExampleSlides(example, t).
// Outlines use the layout ids defined in presentationAssets.getLayoutSpec.
// Content is real academic text — never placeholder filler.

export const presentationExamples = [
  {
    id: 'ex-pres-cyber-security', name: 'Cyber Security', category: 'Information Technology', style: 'Dark', language: 'en',
    description: 'A dark, technology-themed deck covering threats, malware, phishing, protection, and best practices.',
    templateId: 'cyber-security',
    outline: [
      { layout: 'title', title: 'Cyber Security', subtitle: 'Protecting Systems, Networks & Data' },
      { layout: 'titleContent', title: 'Introduction', body: 'Cyber security is the practice of protecting systems, networks, and data from digital attacks aimed at accessing, changing, or destroying sensitive information.' },
      { layout: 'titleBullets', title: 'What is Cyber Security?', bullets: ['Confidentiality of data', 'Integrity of information', 'Availability of systems', 'Protection of identity'] },
      { layout: 'titleBullets', title: 'Common Threats', bullets: ['Malware & viruses', 'Phishing attacks', 'Ransomware', 'Man-in-the-middle'] },
      { layout: 'titleContent', title: 'Malware', body: 'Malicious software such as viruses, worms, and trojans designed to infiltrate, damage, or take control of a system without the user\u2019s consent.' },
      { layout: 'titleContent', title: 'Phishing', body: 'Fraudulent messages that impersonate trusted sources to trick users into revealing passwords, financial details, or other sensitive data.' },
      { layout: 'titleBullets', title: 'Protection Methods', bullets: ['Strong, unique passwords', 'Two-factor authentication', 'Regular software updates', 'Security awareness training'] },
      { layout: 'titleBullets', title: 'Best Practices', bullets: ['Backup data regularly', 'Verify links before clicking', 'Use trusted networks', 'Monitor account activity'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'Good cyber security habits keep your data, identity, and systems safe in an increasingly connected world.' },
      { layout: 'references', title: 'References' },
    ],
  },
  {
    id: 'ex-pres-ai', name: 'Artificial Intelligence', category: 'Computer Science', style: 'Technology', language: 'en',
    description: 'A modern futuristic deck on AI: history, types, applications, benefits, challenges, and the future.',
    templateId: 'dark-technology',
    outline: [
      { layout: 'title', title: 'Artificial Intelligence', subtitle: 'Machines that Learn and Reason' },
      { layout: 'titleContent', title: 'What is AI?', body: 'Artificial intelligence is the science of building systems capable of performing tasks that normally require human intelligence, such as reasoning, learning, and decision-making.' },
      { layout: 'titleBullets', title: 'History', bullets: ['1950s: Early foundations', '1980s: Expert systems', '2010s: Deep learning', 'Today: Generative AI'] },
      { layout: 'titleBullets', title: 'Types of AI', bullets: ['Reactive machines', 'Limited memory', 'Theory of mind', 'Self-aware systems'] },
      { layout: 'titleBullets', title: 'Applications', bullets: ['Healthcare diagnosis', 'Autonomous vehicles', 'Language translation', 'Personal assistants'] },
      { layout: 'titleBullets', title: 'Benefits', bullets: ['Automation of tasks', 'Improved accuracy', 'Faster decisions', 'New insights'] },
      { layout: 'titleBullets', title: 'Challenges', bullets: ['Bias and fairness', 'Privacy concerns', 'Job displacement', 'Safety and control'] },
      { layout: 'titleContent', title: 'Future of AI', body: 'AI is expected to reshape industries through smarter assistants, autonomous systems, and deeper human\u2013AI collaboration across every domain.' },
      { layout: 'conclusion', title: 'Conclusion', body: 'AI is shaping the future of every industry and will continue to transform how we live and work.' },
      { layout: 'references', title: 'References' },
    ],
  },
  {
    id: 'ex-pres-programming', name: 'Programming Fundamentals', category: 'Computer Science', style: 'Technology', language: 'en',
    description: 'A clean coding-themed deck on variables, data types, conditions, loops, and functions.',
    templateId: 'modern-black',
    outline: [
      { layout: 'title', title: 'Programming Fundamentals', subtitle: 'The Building Blocks of Code' },
      { layout: 'titleContent', title: 'Introduction', body: 'Programming is the process of writing instructions that a computer can execute to solve problems and automate tasks.' },
      { layout: 'titleBullets', title: 'Variables', bullets: ['Store data values', 'Have names and types', 'Can be updated', 'Enable reusable logic'] },
      { layout: 'titleBullets', title: 'Data Types', bullets: ['Numbers (int, float)', 'Text (strings)', 'Booleans (true/false)', 'Lists and arrays'] },
      { layout: 'titleBullets', title: 'Conditions', bullets: ['if / else statements', 'Comparisons', 'Logical operators', 'Decision branching'] },
      { layout: 'titleBullets', title: 'Loops', bullets: ['for loops', 'while loops', 'Repeating tasks', 'Iterating collections'] },
      { layout: 'titleBullets', title: 'Functions', bullets: ['Reusable blocks of code', 'Accept inputs', 'Return outputs', 'Improve organization'] },
      { layout: 'titleContent', title: 'Examples', body: 'A simple program reads input, stores it in variables, applies conditions and loops, and calls functions to produce a result.' },
      { layout: 'conclusion', title: 'Conclusion', body: 'Mastering these fundamentals gives you the foundation to build any program in any language.' },
    ],
  },
  {
    id: 'ex-pres-web-dev', name: 'Web Development', category: 'Computer Science', style: 'Technology', language: 'en',
    description: 'A modern developer deck covering HTML, CSS, JavaScript, frontend, backend, and databases.',
    templateId: 'dark-technology',
    outline: [
      { layout: 'title', title: 'Web Development', subtitle: 'Building the Modern Web' },
      { layout: 'titleContent', title: 'Introduction', body: 'Web development is the work of building and maintaining websites and web applications that run in the browser.' },
      { layout: 'titleBullets', title: 'HTML', bullets: ['Structure of pages', 'Elements and tags', 'Semantic markup', 'Forms and links'] },
      { layout: 'titleBullets', title: 'CSS', bullets: ['Styling and layout', 'Colors and fonts', 'Responsive design', 'Flexbox and grid'] },
      { layout: 'titleBullets', title: 'JavaScript', bullets: ['Interactivity', 'DOM manipulation', 'Events', 'APIs and fetch'] },
      { layout: 'titleBullets', title: 'Frontend', bullets: ['User interface', 'Frameworks (React)', 'Performance', 'Accessibility'] },
      { layout: 'titleBullets', title: 'Backend', bullets: ['Servers and APIs', 'Business logic', 'Authentication', 'Databases'] },
      { layout: 'titleContent', title: 'Modern Web Apps', body: 'Modern web apps combine a reactive frontend with a robust backend and a database to deliver fast, dynamic user experiences.' },
      { layout: 'conclusion', title: 'Conclusion', body: 'Web development brings ideas to life on every device connected to the internet.' },
    ],
  },
  {
    id: 'ex-pres-databases', name: 'Database Systems', category: 'Information Technology', style: 'Professional', language: 'en',
    description: 'A professional blue deck on SQL, tables, relationships, keys, queries, and security.',
    templateId: 'modern-blue',
    outline: [
      { layout: 'title', title: 'Database Systems', subtitle: 'Organizing Data Efficiently' },
      { layout: 'titleContent', title: 'Introduction', body: 'A database is an organized collection of data that can be easily accessed, managed, and updated.' },
      { layout: 'titleBullets', title: 'SQL', bullets: ['Structured Query Language', 'Create, read, update, delete', 'Filtering and sorting', 'Joins between tables'] },
      { layout: 'titleBullets', title: 'Tables', bullets: ['Rows and columns', 'Records and fields', 'Data types', 'Constraints'] },
      { layout: 'titleBullets', title: 'Relationships', bullets: ['One-to-one', 'One-to-many', 'Many-to-many', 'Referential integrity'] },
      { layout: 'titleBullets', title: 'Primary Keys', bullets: ['Unique identifiers', 'No null values', 'Indexed for speed', 'Foreign key references'] },
      { layout: 'titleBullets', title: 'Queries', bullets: ['SELECT statements', 'WHERE conditions', 'GROUP BY and aggregates', 'ORDER BY results'] },
      { layout: 'titleBullets', title: 'Security', bullets: ['User permissions', 'Encryption at rest', 'Backups', 'Input validation'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'Well-designed databases are the backbone of reliable, scalable applications.' },
    ],
  },
  {
    id: 'ex-pres-networks', name: 'Computer Networks', category: 'Information Technology', style: 'Technology', language: 'en',
    description: 'A technology-themed deck on network types, protocols, topology, and security.',
    templateId: 'dark-technology',
    outline: [
      { layout: 'title', title: 'Computer Networks', subtitle: 'Connecting the World' },
      { layout: 'titleContent', title: 'Introduction', body: 'A computer network is a set of devices connected to share resources and communicate with each other.' },
      { layout: 'titleBullets', title: 'Network Types', bullets: ['LAN — Local Area', 'MAN — Metropolitan', 'WAN — Wide Area', 'Internet'] },
      { layout: 'titleBullets', title: 'Protocols', bullets: ['TCP/IP', 'HTTP / HTTPS', 'DNS', 'FTP'] },
      { layout: 'titleBullets', title: 'Topology', bullets: ['Star', 'Bus', 'Ring', 'Mesh'] },
      { layout: 'titleBullets', title: 'Devices', bullets: ['Routers', 'Switches', 'Access points', 'Modems'] },
      { layout: 'titleBullets', title: 'Security', bullets: ['Firewalls', 'Encryption', 'VPNs', 'Access control'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'Networks enable communication and resource sharing on a global scale.' },
    ],
  },
  {
    id: 'ex-pres-graphic-design', name: 'Graphic Design', category: 'Creative', style: 'Creative', language: 'en',
    description: 'A colorful, creative deck on design principles, color, typography, and composition.',
    templateId: 'creative-student',
    outline: [
      { layout: 'title', title: 'Graphic Design', subtitle: 'Visual Communication' },
      { layout: 'titleContent', title: 'Introduction', body: 'Graphic design is the art of combining text, images, and ideas to communicate messages visually.' },
      { layout: 'titleBullets', title: 'Design Principles', bullets: ['Balance', 'Contrast', 'Alignment', 'Hierarchy'] },
      { layout: 'titleBullets', title: 'Color', bullets: ['Color wheel', 'Warm vs cool', 'Brand palettes', 'Accessibility'] },
      { layout: 'titleBullets', title: 'Typography', bullets: ['Font pairing', 'Readability', 'Scale and weight', 'Spacing'] },
      { layout: 'titleBullets', title: 'Composition', bullets: ['Grid systems', 'White space', 'Focal points', 'Rule of thirds'] },
      { layout: 'titleBullets', title: 'Tools', bullets: ['Vector graphics', 'Photo editing', 'Layout software', 'Prototyping'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'Strong design combines creativity with structure to deliver clear, memorable messages.' },
    ],
  },
  {
    id: 'ex-pres-cloud', name: 'Cloud Computing', category: 'Information Technology', style: 'Technology', language: 'en',
    description: 'A modern cloud-themed deck on service models, deployment, benefits, and providers.',
    templateId: 'dark-technology',
    outline: [
      { layout: 'title', title: 'Cloud Computing', subtitle: 'On-Demand Computing Power' },
      { layout: 'titleContent', title: 'Introduction', body: 'Cloud computing delivers computing services — servers, storage, databases, and software — over the internet.' },
      { layout: 'titleBullets', title: 'Service Models', bullets: ['IaaS — Infrastructure', 'PaaS — Platform', 'SaaS — Software', 'FaaS — Functions'] },
      { layout: 'titleBullets', title: 'Deployment', bullets: ['Public cloud', 'Private cloud', 'Hybrid cloud', 'Multi-cloud'] },
      { layout: 'titleBullets', title: 'Benefits', bullets: ['Scalability', 'Cost efficiency', 'Reliability', 'Global access'] },
      { layout: 'titleBullets', title: 'Providers', bullets: ['Amazon Web Services', 'Microsoft Azure', 'Google Cloud', 'Others'] },
      { layout: 'titleBullets', title: 'Security', bullets: ['Shared responsibility', 'Identity management', 'Data encryption', 'Compliance'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'The cloud enables organizations to innovate faster without managing physical infrastructure.' },
    ],
  },
  {
    id: 'ex-pres-iot', name: 'Internet of Things', category: 'Information Technology', style: 'Technology', language: 'en',
    description: 'A smart-devices deck on IoT architecture, applications, benefits, and challenges.',
    templateId: 'dark-technology',
    outline: [
      { layout: 'title', title: 'Internet of Things', subtitle: 'A World of Connected Devices' },
      { layout: 'titleContent', title: 'Introduction', body: 'The Internet of Things (IoT) is a network of physical objects embedded with sensors and software that connect and exchange data over the internet.' },
      { layout: 'titleBullets', title: 'Architecture', bullets: ['Sensors and devices', 'Connectivity', 'Data processing', 'User interface'] },
      { layout: 'titleBullets', title: 'Applications', bullets: ['Smart homes', 'Healthcare', 'Industrial IoT', 'Smart cities'] },
      { layout: 'titleBullets', title: 'Benefits', bullets: ['Automation', 'Efficiency', 'Real-time insights', 'Remote monitoring'] },
      { layout: 'titleBullets', title: 'Challenges', bullets: ['Security', 'Privacy', 'Interoperability', 'Power consumption'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'IoT connects the physical and digital worlds, enabling smarter decisions and automation.' },
    ],
  },
  {
    id: 'ex-pres-digital-marketing', name: 'Digital Marketing', category: 'Business', style: 'Professional', language: 'en',
    description: 'A professional marketing deck on channels, strategy, content, and analytics.',
    templateId: 'pro-business',
    outline: [
      { layout: 'title', title: 'Digital Marketing', subtitle: 'Reaching Customers Online' },
      { layout: 'titleContent', title: 'Introduction', body: 'Digital marketing promotes products and services using digital channels to reach and engage target audiences.' },
      { layout: 'titleBullets', title: 'Channels', bullets: ['Search engines (SEO)', 'Social media', 'Email', 'Content marketing'] },
      { layout: 'titleBullets', title: 'Strategy', bullets: ['Define audience', 'Set goals', 'Choose channels', 'Measure results'] },
      { layout: 'titleBullets', title: 'Content', bullets: ['Blogs and articles', 'Video', 'Graphics', 'Storytelling'] },
      { layout: 'titleBullets', title: 'Analytics', bullets: ['Traffic sources', 'Conversion rates', 'Engagement', 'ROI tracking'] },
      { layout: 'titleBullets', title: 'Advertising', bullets: ['Pay-per-click', 'Social ads', 'Display networks', 'Retargeting'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'Data-driven digital marketing connects the right message with the right audience at the right time.' },
    ],
  },
  {
    id: 'ex-pres-business-plan', name: 'Business Plan', category: 'Business', style: 'Professional', language: 'en',
    description: 'A premium business deck: problem, solution, market, product, model, marketing, and financials.',
    templateId: 'pro-business',
    outline: [
      { layout: 'title', title: 'Business Plan', subtitle: 'From Idea to Execution' },
      { layout: 'titleContent', title: 'Problem', body: 'A clear description of the customer problem or market gap your business aims to solve.' },
      { layout: 'titleContent', title: 'Solution', body: 'The product or service you offer and how it addresses the problem better than existing alternatives.' },
      { layout: 'titleBullets', title: 'Market', bullets: ['Target customers', 'Market size', 'Competitors', 'Opportunities'] },
      { layout: 'titleBullets', title: 'Product', bullets: ['Key features', 'Value proposition', 'Differentiation', 'Roadmap'] },
      { layout: 'titleBullets', title: 'Business Model', bullets: ['Revenue streams', 'Pricing', 'Channels', 'Cost structure'] },
      { layout: 'titleBullets', title: 'Marketing', bullets: ['Positioning', 'Acquisition', 'Retention', 'Partnerships'] },
      { layout: 'titleBullets', title: 'Financial Overview', bullets: ['Revenue projection', 'Costs', 'Break-even', 'Funding needs'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'A solid business plan turns a vision into an actionable, fundable roadmap.' },
    ],
  },
  {
    id: 'ex-pres-startup-pitch', name: 'Startup Pitch', category: 'Business', style: 'Modern', language: 'en',
    description: 'A modern startup pitch deck: problem, solution, market, product, traction, team, and ask.',
    templateId: 'purple-gradient',
    outline: [
      { layout: 'title', title: 'Startup Pitch', subtitle: 'Invest in the Future' },
      { layout: 'titleContent', title: 'The Problem', body: 'Describe the pain point your customers face and why current solutions fall short.' },
      { layout: 'titleContent', title: 'The Solution', body: 'Explain your product and how it solves the problem in a simpler, faster, or cheaper way.' },
      { layout: 'titleBullets', title: 'Market Opportunity', bullets: ['Total addressable market', 'Target segment', 'Growth trends', 'Timing'] },
      { layout: 'titleBullets', title: 'Product', bullets: ['How it works', 'Key features', 'Technology', 'User experience'] },
      { layout: 'titleBullets', title: 'Traction', bullets: ['Users and growth', 'Revenue', 'Key metrics', 'Milestones'] },
      { layout: 'titleBullets', title: 'Team', bullets: ['Founders', 'Experience', 'Roles', 'Advisors'] },
      { layout: 'titleContent', title: 'The Ask', body: 'State the investment you are raising, how the funds will be used, and the milestones they will unlock.' },
      { layout: 'conclusion', title: 'Conclusion', body: 'A great pitch tells a compelling story backed by numbers and a clear plan.' },
    ],
  },
  {
    id: 'ex-pres-scientific-research', name: 'Scientific Research', category: 'Research', style: 'Academic', language: 'en',
    description: 'A clean academic deck: background, problem, objectives, method, results, discussion, conclusion.',
    templateId: 'research',
    outline: [
      { layout: 'title', title: 'Scientific Research', subtitle: 'A Structured Study' },
      { layout: 'titleContent', title: 'Background', body: 'Context and prior work that motivates the research question.' },
      { layout: 'titleContent', title: 'Problem Statement', body: 'The specific gap or issue this research addresses.' },
      { layout: 'titleBullets', title: 'Objectives', bullets: ['Primary aim', 'Secondary aims', 'Research questions', 'Hypotheses'] },
      { layout: 'titleBullets', title: 'Method', bullets: ['Study design', 'Data collection', 'Analysis approach', 'Tools used'] },
      { layout: 'titleBullets', title: 'Results', bullets: ['Key findings', 'Quantitative results', 'Qualitative results', 'Statistical significance'] },
      { layout: 'titleContent', title: 'Discussion', body: 'Interpretation of results, comparison with prior work, and limitations of the study.' },
      { layout: 'conclusion', title: 'Conclusion', body: 'Summary of contributions and directions for future research.' },
      { layout: 'references', title: 'References' },
    ],
  },
  {
    id: 'ex-pres-university-seminar', name: 'University Seminar', category: 'Education', style: 'Academic', language: 'en',
    description: 'A classic academic seminar deck with introduction, key points, analysis, and conclusion.',
    templateId: 'university-classic',
    outline: [
      { layout: 'title', title: 'University Seminar', subtitle: 'An Academic Presentation' },
      { layout: 'titleContent', title: 'Introduction', body: 'An overview of the seminar topic, its importance, and the objectives of the session.' },
      { layout: 'titleBullets', title: 'Key Points', bullets: ['Background', 'Core concepts', 'Main arguments', 'Evidence'] },
      { layout: 'titleContent', title: 'Analysis', body: 'A detailed examination of the main points with supporting examples and references.' },
      { layout: 'titleBullets', title: 'Discussion', bullets: ['Implications', 'Comparisons', 'Open questions', 'Applications'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'Summary of insights, key takeaways, and suggestions for further study.' },
      { layout: 'references', title: 'References' },
    ],
  },
  {
    id: 'ex-pres-environment', name: 'Environmental Sustainability', category: 'Environment', style: 'Modern', language: 'en',
    description: 'A green, nature-themed deck on sustainability challenges, solutions, and action.',
    templateId: 'elegant-green',
    outline: [
      { layout: 'title', title: 'Environmental Sustainability', subtitle: 'Protecting Our Planet' },
      { layout: 'titleContent', title: 'Introduction', body: 'Sustainability means meeting present needs without compromising the ability of future generations to meet theirs.' },
      { layout: 'titleBullets', title: 'Key Challenges', bullets: ['Climate change', 'Pollution', 'Resource depletion', 'Biodiversity loss'] },
      { layout: 'titleBullets', title: 'Solutions', bullets: ['Renewable energy', 'Recycling', 'Conservation', 'Sustainable agriculture'] },
      { layout: 'titleBullets', title: 'Individual Action', bullets: ['Reduce and reuse', 'Save energy', 'Eco-friendly transport', 'Responsible consumption'] },
      { layout: 'titleBullets', title: 'Policy & Innovation', bullets: ['Green regulations', 'Clean technology', 'Circular economy', 'Corporate responsibility'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'A sustainable future depends on the combined efforts of individuals, organizations, and governments.' },
    ],
  },
  {
    id: 'ex-pres-health-tech', name: 'Health & Technology', category: 'Health', style: 'Modern', language: 'en',
    description: 'A clean health/technology deck on digital health, telemedicine, devices, and data.',
    templateId: 'modern-blue',
    outline: [
      { layout: 'title', title: 'Health & Technology', subtitle: 'Digital Health in Action' },
      { layout: 'titleContent', title: 'Introduction', body: 'Health technology uses digital tools to improve patient care, diagnosis, and access to medical services.' },
      { layout: 'titleBullets', title: 'Telemedicine', bullets: ['Remote consultations', 'Accessibility', 'Cost savings', 'Continuity of care'] },
      { layout: 'titleBullets', title: 'Wearables', bullets: ['Activity tracking', 'Vital signs', 'Early warnings', 'Patient engagement'] },
      { layout: 'titleBullets', title: 'Health Data', bullets: ['Electronic records', 'Analytics', 'Privacy', 'Interoperability'] },
      { layout: 'titleBullets', title: 'AI in Healthcare', bullets: ['Diagnosis support', 'Drug discovery', 'Personalized care', 'Workflow automation'] },
      { layout: 'conclusion', title: 'Conclusion', body: 'Technology is making healthcare more accessible, accurate, and patient-centered.' },
    ],
  },
  {
    id: 'ex-pres-mathematics', name: 'Mathematics', category: 'Science', style: 'Academic', language: 'en',
    description: 'A modern academic deck with equations and structured visual layouts.',
    templateId: 'research',
    outline: [
      { layout: 'title', title: 'Mathematics', subtitle: 'The Language of Science' },
      { layout: 'titleContent', title: 'Introduction', body: 'Mathematics provides the formal language and tools used to model, analyze, and solve problems across science and engineering.' },
      { layout: 'titleBullets', title: 'Core Areas', bullets: ['Algebra', 'Calculus', 'Geometry', 'Statistics'] },
      { layout: 'titleContent', title: 'Linear Equations', body: 'A linear equation has the form y = mx + b, describing a straight line with slope m and intercept b.' },
      { layout: 'titleContent', title: 'Quadratic Formula', body: 'The roots of ax\u00b2 + bx + c = 0 are given by x = (-b \u00b1 \u221a(b\u00b2 - 4ac)) / 2a.' },
      { layout: 'titleBullets', title: 'Applications', bullets: ['Engineering', 'Computer science', 'Economics', 'Physics'] },
      { layout: 'titleContent', title: 'Proofs & Logic', body: 'Mathematical proofs use logical reasoning to establish the truth of statements from accepted axioms and theorems.' },
      { layout: 'conclusion', title: 'Conclusion', body: 'Mathematics is the foundation of precise reasoning and quantitative understanding.' },
    ],
  },
  {
    id: 'ex-pres-minimal', name: 'Minimal Academic Presentation', category: 'Minimal', style: 'Minimal', language: 'en',
    description: 'A very clean, elegant deck with lots of whitespace and strong typography.',
    templateId: 'minimal-white',
    outline: [
      { layout: 'title', title: 'A Minimal Presentation', subtitle: 'Clarity Through Simplicity' },
      { layout: 'section', title: 'Introduction' },
      { layout: 'titleContent', title: 'The Idea', body: 'A single, clear idea presented with space and focus is more powerful than a crowded slide.' },
      { layout: 'quote', title: '' },
      { layout: 'titleBullets', title: 'Principles', bullets: ['One idea per slide', 'Strong typography', 'Generous whitespace', 'Clear hierarchy'] },
      { layout: 'titleContent', title: 'Structure', body: 'A minimal deck guides the audience through a clear narrative without visual distraction.' },
      { layout: 'conclusion', title: 'Conclusion', body: 'Less, but better — focus on what matters most.' },
    ],
  },
];

export default presentationExamples;