// Master report & assignment examples (read-only templates).
// Each spec produces a full report project (content) with real HTML body content,
// a cover page, and references. Uses reportModel + reportAssets builders.

import { createReportProject } from '@/lib/reportModel';
import { getTemplate, PLACEHOLDER_IMG } from '@/lib/reportAssets';

function esc(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
const p = (t) => `<p>${esc(t)}</p>`;
const h = (id, t) => `<h2 data-rd-id="sec-${id}">${esc(t)}</h2>`;
const ul = (items) => `<ul>${items.map((i) => `<li>${esc(i)}</li>`).join('')}</ul>`;
const fig = (n, cap) => `<div class="rd-fig" style="text-align:center;" data-rd-fig="${n}"><img src="${PLACEHOLDER_IMG}" style="width:70%;border-radius:6px;" alt="figure"><p class="rd-caption">Figure ${n}: ${esc(cap)}</p></div>`;
const table = (headers, rows) => {
  const th = headers.map((x) => `<th style="border:1px solid #cbd5e1;padding:8px;text-align:left;background:#e2e8f0;">${esc(x)}</th>`).join('');
  const trs = rows.map((r) => `<tr>${r.map((c) => `<td style="border:1px solid #cbd5e1;padding:8px;">${esc(c)}</td>`).join('')}</tr>`).join('');
  return `<table style="border-collapse:collapse;width:100%;"><thead><tr>${th}</tr></thead><tbody>${trs}</tbody></table>`;
};
const code = (src) => `<pre style="background:#0f172a;color:#e2e8f0;padding:12px;border-radius:8px;overflow:auto;font-family:ui-monospace,monospace;font-size:13px;">${esc(src)}</pre>`;
const refsBlock = () => '<div class="rd-refs" data-rd-refs="1"></div>';
const toc = () => '<div class="rd-toc" data-toc="1"></div>';

// Each example: id, name, category, style, language, description, template, coverLayout, refs[], build() -> html
export const reportExamples = [
  {
    id: 'ex-rep-cyber-security', name: 'Cyber Security Report', category: 'Information Technology', style: 'Technology', language: 'en',
    description: 'A full cyber security report with cover, TOC, threats, methods, recommendations, and references.',
    template: 'itproject', coverLayout: 'modern',
    refs: [
      { author: 'Smith, J.', title: 'Introduction to Cyber Security', year: '2022', publisher: 'Academic Press', link: 'https://example.com/cyber' },
      { author: 'Khan, R.', title: 'Modern Threat Detection Techniques', year: '2023', publisher: 'IEEE', link: 'https://example.com/threats' },
    ],
    build: () => [
      toc(),
      h('introduction', 'Introduction'),
      p('Cyber security is the practice of protecting systems, networks, and programs from digital attacks. These attacks aim to access, change, or destroy sensitive information, extort money from users, or interrupt normal business processes.'),
      p('In today\u2019s connected world, cyber security has become essential for individuals, organizations, and governments. This report introduces the most common cyber threats and the methods used to protect against them.'),
      h('threats', 'Cyber Threats'),
      p('There are several categories of cyber threats that target users and organizations every day:'),
      ul(['Malware — malicious software such as viruses, worms, and trojans.', 'Phishing — fraudulent messages that trick users into revealing sensitive data.', 'Ransomware — malware that encrypts files and demands payment.', 'Man-in-the-middle — attackers intercept communication between two parties.']),
      fig(1, 'Common cyber threat categories.'),
      h('methods', 'Security Methods'),
      p('Effective protection combines technology, processes, and user awareness. The table below summarizes key protection methods:'),
      table(['Method', 'Description'], [['Strong passwords', 'Use long, unique passwords for each account.'], ['Multi-factor authentication', 'Require a second verification step at login.'], ['Software updates', 'Keep systems patched against known vulnerabilities.'], ['Backups', 'Maintain offline copies of critical data.']]),
      h('recommendations', 'Recommendations'),
      ul(['Enable multi-factor authentication on all accounts.', 'Train users to recognize phishing attempts.', 'Maintain regular, tested backups.', 'Monitor systems for unusual activity.']),
      h('conclusion', 'Conclusion'),
      p('Cyber security is an ongoing process that requires attention from every user. By understanding common threats and applying basic protection methods, individuals and organizations can greatly reduce their risk.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-ai', name: 'Artificial Intelligence Report', category: 'Computer Science', style: 'Technology', language: 'en',
    description: 'A report on AI: introduction, types, applications, benefits, challenges, and conclusion.',
    template: 'itproject', coverLayout: 'modern',
    refs: [{ author: 'Russell, S.', title: 'Artificial Intelligence: A Modern Approach', year: '2021', publisher: 'Pearson', link: '' }],
    build: () => [
      toc(),
      h('introduction', 'Introduction'),
      p('Artificial intelligence (AI) is the science of building systems capable of performing tasks that normally require human intelligence, such as reasoning, learning, and decision-making.'),
      h('types', 'Types of AI'),
      ul(['Reactive machines', 'Limited memory', 'Theory of mind', 'Self-aware systems']),
      h('applications', 'Applications'),
      p('AI is applied across many fields, including healthcare, finance, transportation, and education.'),
      ul(['Medical diagnosis', 'Autonomous vehicles', 'Language translation', 'Personal assistants']),
      fig(1, 'AI application domains.'),
      h('benefits', 'Benefits'),
      ul(['Automation of repetitive tasks', 'Improved accuracy and speed', 'New insights from data']),
      h('challenges', 'Challenges'),
      ul(['Bias and fairness', 'Privacy concerns', 'Job displacement', 'Safety and control']),
      h('conclusion', 'Conclusion'),
      p('AI offers enormous potential but requires responsible development and thoughtful regulation.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-programming', name: 'Programming Assignment', category: 'Computer Science', style: 'Technology', language: 'en',
    description: 'A programming assignment with problem, explanation, code, result, and conclusion.',
    template: 'itproject', coverLayout: 'classic',
    refs: [{ author: 'Kernighan, B.', title: 'The C Programming Language', year: '1988', publisher: 'Prentice Hall', link: '' }],
    build: () => [
      toc(),
      h('problem', 'Problem Statement'),
      p('Write a program that reads a list of numbers and prints their sum and average.'),
      h('explanation', 'Explanation'),
      p('The program iterates over the input values, accumulates their sum, and divides by the count to compute the average.'),
      h('code', 'Code'),
      code('numbers = [10, 20, 30, 40]\ntotal = sum(numbers)\naverage = total / len(numbers)\nprint("Sum:", total)\nprint("Average:", average)'),
      h('result', 'Result'),
      p('For the input [10, 20, 30, 40], the program outputs Sum: 100 and Average: 25.0.'),
      table(['Input', 'Sum', 'Average'], [['10,20,30,40', '100', '25.0'], ['5,15,25', '45', '15.0']]),
      h('conclusion', 'Conclusion'),
      p('The assignment demonstrates basic iteration, accumulation, and arithmetic in a simple program.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-database', name: 'Database Assignment', category: 'Information Technology', style: 'Professional', language: 'en',
    description: 'A database assignment with tables, SQL examples, results, and conclusion.',
    template: 'problue', coverLayout: 'modern',
    refs: [{ author: 'Silberschatz, A.', title: 'Database System Concepts', year: '2019', publisher: 'McGraw-Hill', link: '' }],
    build: () => [
      toc(),
      h('introduction', 'Introduction'),
      p('This assignment explores basic relational database concepts using SQL.'),
      h('tables', 'Tables'),
      p('Consider two tables: Students and Enrollments.'),
      table(['Students(id, name, stage)', 'Enrollments(student_id, course)'], [['1, Ali, 2', '1, Databases'], ['2, Sara, 3', '2, Networks']]),
      h('sql', 'SQL Examples'),
      code("SELECT name, stage FROM Students;\nSELECT s.name, e.course\nFROM Students s\nJOIN Enrollments e ON s.id = e.student_id;"),
      h('results', 'Results'),
      p('The join query returns each student with their enrolled courses.'),
      table(['Student', 'Course'], [['Ali', 'Databases'], ['Sara', 'Networks']]),
      h('conclusion', 'Conclusion'),
      p('The assignment demonstrates table creation, joins, and basic queries.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-web-dev', name: 'Web Development Report', category: 'Computer Science', style: 'Technology', language: 'en',
    description: 'A report on web development: HTML, CSS, JavaScript, frontend, backend, and databases.',
    template: 'itproject', coverLayout: 'modern',
    refs: [{ author: 'MDN', title: 'Web Docs', year: '2024', publisher: 'Mozilla', link: 'https://developer.mozilla.org' }],
    build: () => [
      toc(),
      h('introduction', 'Introduction'),
      p('Web development is the work of building and maintaining websites and web applications.'),
      h('html', 'HTML'),
      p('HTML provides the structure of web pages using elements and tags.'),
      h('css', 'CSS'),
      p('CSS controls the styling and layout of pages, including responsive design.'),
      h('javascript', 'JavaScript'),
      p('JavaScript adds interactivity, handles events, and communicates with APIs.'),
      code("fetch('/api/data').then(r => r.json()).then(data => console.log(data));"),
      h('frontend', 'Frontend'),
      ul(['User interface', 'Frameworks like React', 'Performance and accessibility']),
      h('backend', 'Backend'),
      ul(['Servers and APIs', 'Business logic', 'Authentication']),
      h('conclusion', 'Conclusion'),
      p('Modern web development combines frontend and backend skills to build complete applications.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-networks', name: 'Computer Networks Report', category: 'Information Technology', style: 'Technology', language: 'en',
    description: 'A report on network types, protocols, topology, devices, and security.',
    template: 'itproject', coverLayout: 'classic',
    refs: [{ author: 'Tanenbaum, A.', title: 'Computer Networks', year: '2020', publisher: 'Pearson', link: '' }],
    build: () => [
      toc(),
      h('introduction', 'Introduction'),
      p('A computer network is a set of devices connected to share resources and communicate.'),
      h('types', 'Network Types'),
      ul(['LAN — Local Area Network', 'MAN — Metropolitan Area Network', 'WAN — Wide Area Network', 'The Internet']),
      h('protocols', 'Protocols'),
      ul(['TCP/IP', 'HTTP/HTTPS', 'DNS', 'FTP']),
      h('topology', 'Topology'),
      ul(['Star', 'Bus', 'Ring', 'Mesh']),
      h('security', 'Security'),
      ul(['Firewalls', 'Encryption', 'VPNs', 'Access control']),
      h('conclusion', 'Conclusion'),
      p('Networks enable communication and resource sharing on a global scale.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-research', name: 'Research Report', category: 'Research', style: 'Academic', language: 'en',
    description: 'A full research report: abstract, introduction, literature, methodology, results, discussion, conclusion.',
    template: 'research', coverLayout: 'formal',
    refs: [
      { author: 'Creswell, J.', title: 'Research Design', year: '2018', publisher: 'Sage', link: '' },
      { author: 'Yin, R.', title: 'Case Study Research', year: '2017', publisher: 'Sage', link: '' },
    ],
    build: () => [
      toc(),
      h('abstract', 'Abstract'),
      p('This research report presents the study objectives, methodology, main results, and conclusions in a concise summary.'),
      h('introduction', 'Introduction'),
      p('The introduction outlines the research problem, its significance, and the questions this study addresses.'),
      h('literature', 'Literature Review'),
      p('Prior work is reviewed to establish the context and identify the gap this study fills.'),
      h('methodology', 'Methodology'),
      p('The methodology describes the approach, data collection, and analysis techniques used in the study.'),
      ul(['Study design', 'Sample selection', 'Data collection', 'Analysis']),
      h('results', 'Results'),
      p('The results section presents the findings obtained from the applied methodology.'),
      table(['Metric', 'Value'], [['Participants', '120'], ['Response rate', '92%']]),
      h('discussion', 'Discussion'),
      p('The discussion interprets the results and compares them with previous work.'),
      h('conclusion', 'Conclusion'),
      p('The conclusion states the main outcomes and suggests directions for future research.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-university-assignment', name: 'University Assignment', category: 'Education', style: 'Academic', language: 'en',
    description: 'A simple academic assignment with introduction, discussion, and conclusion.',
    template: 'assignment', coverLayout: 'classic',
    refs: [{ author: 'Booth, W.', title: 'The Craft of Research', year: '2016', publisher: 'Chicago', link: '' }],
    build: () => [
      toc(),
      h('introduction', 'Introduction'),
      p('This assignment discusses the chosen topic and presents the main arguments supported by evidence.'),
      h('discussion', 'Main Discussion'),
      p('The discussion develops the key points, analyzes different perspectives, and connects them to the introduction.'),
      ul(['First key point with supporting detail.', 'Second key point with an example.', 'Third key point and its implications.']),
      h('conclusion', 'Conclusion'),
      p('The conclusion summarizes the findings and restates the main argument of the assignment.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-scientific', name: 'Scientific Report', category: 'Science', style: 'Academic', language: 'en',
    description: 'A professional research layout with abstract, method, results, and discussion.',
    template: 'scientific', coverLayout: 'formal',
    refs: [{ author: 'Day, R.', title: 'How to Write and Publish a Scientific Paper', year: '2012', publisher: 'Cambridge', link: '' }],
    build: () => [
      toc(),
      h('abstract', 'Abstract'),
      p('A concise summary of the experiment, its purpose, methods, results, and conclusions.'),
      h('introduction', 'Introduction'),
      p('The background and rationale for the experiment.'),
      h('methodology', 'Methodology'),
      p('The experimental setup, materials, and procedures.'),
      h('results', 'Results'),
      p('The measured outcomes, presented with figures and tables.'),
      table(['Sample', 'Measurement'], [['A', '4.2'], ['B', '5.1'], ['C', '3.8']]),
      h('discussion', 'Discussion'),
      p('Interpretation of the results and their significance.'),
      h('conclusion', 'Conclusion'),
      p('The experiment confirms the hypothesis within the tested conditions.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-project-doc', name: 'Project Documentation', category: 'Information Technology', style: 'Professional', language: 'en',
    description: 'Project documentation: overview, requirements, design, implementation, testing, results.',
    template: 'itproject', coverLayout: 'modern',
    refs: [{ author: 'Sommerville, I.', title: 'Software Engineering', year: '2015', publisher: 'Pearson', link: '' }],
    build: () => [
      toc(),
      h('overview', 'Project Overview'),
      p('A description of the project, its goals, and its scope.'),
      h('requirements', 'Requirements'),
      ul(['Functional requirements', 'Non-functional requirements', 'Constraints']),
      h('design', 'Design'),
      p('The architecture and key components of the system.'),
      fig(1, 'System architecture diagram.'),
      h('implementation', 'Implementation'),
      p('The technologies used and how the components were built.'),
      h('testing', 'Testing'),
      ul(['Unit tests', 'Integration tests', 'User acceptance testing']),
      h('results', 'Results'),
      p('The system meets all requirements and passes the test suite.'),
      h('conclusion', 'Conclusion'),
      p('The project is complete and ready for deployment.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-business', name: 'Business Report', category: 'Business', style: 'Professional', language: 'en',
    description: 'A professional corporate business report with introduction, results, and recommendations.',
    template: 'business', coverLayout: 'modern',
    refs: [{ author: 'Porter, M.', title: 'Competitive Strategy', year: '2004', publisher: 'Free Press', link: '' }],
    build: () => [
      toc(),
      h('introduction', 'Introduction'),
      p('This report summarizes the company\u2019s performance and strategic outlook.'),
      h('results', 'Results'),
      p('Key performance indicators for the period are summarized below.'),
      table(['Indicator', 'Q1', 'Q2'], [['Revenue', '$120k', '$150k'], ['Growth', '8%', '12%']]),
      h('recommendations', 'Recommendations'),
      ul(['Expand into new markets', 'Invest in product development', 'Improve customer retention']),
      h('conclusion', 'Conclusion'),
      p('The company is on a strong growth trajectory with clear opportunities ahead.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-internship', name: 'Internship Report', category: 'Education', style: 'Academic', language: 'en',
    description: 'An internship report: organization, responsibilities, experience, skills, conclusion.',
    template: 'problue', coverLayout: 'classic',
    refs: [{ author: 'University', title: 'Internship Guidelines', year: '2024', publisher: 'University', link: '' }],
    build: () => [
      toc(),
      h('organization', 'Organization'),
      p('A description of the host organization and its field of activity.'),
      h('responsibilities', 'Responsibilities'),
      ul(['Assigned tasks and projects', 'Daily duties', 'Collaboration with teams']),
      h('experience', 'Experience'),
      p('Reflections on the internship experience and the challenges encountered.'),
      h('skills', 'Skills Gained'),
      ul(['Technical skills', 'Communication', 'Teamwork', 'Time management']),
      h('conclusion', 'Conclusion'),
      p('The internship provided valuable practical experience and professional growth.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-minimal', name: 'Minimal Academic Report', category: 'Minimal', style: 'Minimal', language: 'en',
    description: 'A very clean black/white academic report.',
    template: 'minimal', coverLayout: 'minimal',
    refs: [{ author: 'Strunk, W.', title: 'The Elements of Style', year: '2000', publisher: 'Longman', link: '' }],
    build: () => [
      toc(),
      h('introduction', 'Introduction'),
      p('A short, focused report written in a clean, minimal style.'),
      h('discussion', 'Discussion'),
      p('The main argument is presented clearly and concisely.'),
      h('conclusion', 'Conclusion'),
      p('A brief, direct conclusion.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-problue', name: 'Professional Blue Report', category: 'General', style: 'Professional', language: 'en',
    description: 'A modern university document with a professional blue cover.',
    template: 'problue', coverLayout: 'modern',
    refs: [{ author: 'Author', title: 'Reference Title', year: '2023', publisher: 'Publisher', link: '' }],
    build: () => [
      toc(),
      h('introduction', 'Introduction'),
      p('A modern, professionally formatted report suitable for university submission.'),
      h('methodology', 'Methodology'),
      p('The approach and methods used in the study.'),
      h('results', 'Results'),
      p('The findings of the study.'),
      h('conclusion', 'Conclusion'),
      p('A summary of the report\u2019s main points.'),
      refsBlock(),
    ].join(''),
  },
  {
    id: 'ex-rep-graduation', name: 'Graduation Project Report', category: 'Education', style: 'Academic', language: 'en',
    description: 'A full graduation project report with acknowledgement, abstract, TOC, and all chapters.',
    template: 'classic', coverLayout: 'formal',
    refs: [
      { author: 'Supervisor', title: 'Project Approval', year: '2026', publisher: 'University', link: '' },
      { author: 'Author', title: 'Related Work', year: '2024', publisher: 'Journal', link: '' },
    ],
    build: () => [
      h('acknowledgement', 'Acknowledgement'),
      p('I would like to thank my supervisor and the department for their guidance and support throughout this project.'),
      toc(),
      h('abstract', 'Abstract'),
      p('A concise summary of the graduation project, its objectives, methods, and results.'),
      h('introduction', 'Introduction'),
      p('The introduction presents the background and motivation for the project.'),
      h('problem', 'Problem Statement'),
      p('A clear statement of the problem the project solves.'),
      h('objectives', 'Objectives'),
      ul(['Primary objective', 'Secondary objectives', 'Expected outcomes']),
      h('methodology', 'Methodology'),
      p('The methods and tools used to develop the project.'),
      h('implementation', 'Implementation'),
      p('The implementation details and technologies used.'),
      fig(1, 'System architecture.'),
      h('results', 'Results'),
      p('The outcomes and evaluation of the project.'),
      h('conclusion', 'Conclusion'),
      p('The project meets its objectives and contributes to its field.'),
      refsBlock(),
    ].join(''),
  },
];

export function buildReportExampleProject(example) {
  const tpl = getTemplate(example.template);
  const proj = createReportProject({
    title: example.name,
    subtitle: '',
    category: 'report',
    language: example.language,
    templateId: example.template,
    blank: true,
    studentInfo: { title: example.name, students: [{ name: '', id: '' }], university: '' },
  });
  proj.content.html = example.build();
  proj.content.references = { ...proj.content.references, items: example.refs || [] };
  proj.content.cover = { ...proj.content.cover, layout: example.coverLayout || 'classic', primaryColor: tpl.colors.primary, fontFamily: tpl.fonts.heading };
  proj.content.template = example.template;
  proj.content.fontFamily = tpl.fonts.body;
  return proj;
}

export default reportExamples;